import {chromium} from '../../ThirdRailify-Admin/node_modules/playwright-core/index.mjs';
import {mkdir,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const directory='X:/GIT/ThirdRailify-Lab/.artifacts/browser/gold-violet-'+Date.now();await mkdir(directory,{recursive:true});
const headed=process.env.LAB_BROWSER_HEADED==='1';
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:!headed});
const evidence=[];
try{for(const [width,height]of [[1920,1080],[1440,900],[768,1024],[390,844]]){
 const context=await browser.newContext({viewport:{width,height}});await context.addCookies([{name:'thirdrailify_session',value:'local-browser-fixture-token-12345678901234567890',url:'http://127.0.0.1:8798',httpOnly:true,sameSite:'Lax'}]);const page=await context.newPage(),errors=[];await page.route('https://cse.google.com/cse.js**',route=>route.fulfill({contentType:'text/javascript',body:`(()=>{const elements={};window.google={search:{cse:{element:{render(o){const host=document.getElementById(o.div);host.innerHTML='<div class="gsc-control-cse"><div class="gsc-branding">Enhanced by Google</div><div class="gsc-results"></div></div>';elements[o.gname]={execute(query){const cb=window.__gcse.searchCallbacks.image;query=cb.starting(o.gname,query);const result={title:'Gold violet studio reference',url:'https://fixture.images.example/reference.png',visibleUrl:'fixture.example/reference',contextUrl:'https://fixture.example/reference',image:{url:'https://fixture.images.example/reference.png',width:1,height:1},thumbnailImage:{url:'https://fixture.images.example/reference.png',width:1,height:1},fileFormat:'image/png'};cb.ready(o.gname,query,[],[result],host.querySelector('.gsc-results'));host.querySelector('.gsc-results').innerHTML='<div class="gsc-imageResult"><strong>Gold violet studio reference</strong><span>fixture.example</span></div>';cb.rendered(o.gname,query,[],[result]);}};},getElement(name){return elements[name];}}}}};window.__gcse.initializationCallback();})();`}));page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=500)errors.push(`${r.status()} ${r.url()}`);});page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('Failed to load resource'))errors.push(m.text());});
 await page.goto('http://127.0.0.1:8798/');await page.waitForFunction(()=>document.body.dataset.ready==='true');await page.locator('#accountTrigger').filter({hasText:'Workshop Test'}).waitFor();await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:`${directory}/studio-${width}.png`,fullPage:true});
 const layout=await page.evaluate(()=>{const shellNode=document.querySelector('#stageShell'),shell=shellNode.getBoundingClientRect(),stage=document.querySelector('#stage').getBoundingClientRect(),root=getComputedStyle(document.documentElement),scroll=getComputedStyle(document.documentElement,'::-webkit-scrollbar-thumb'),footer=getComputedStyle(document.querySelector('.statusbar')),chip=getComputedStyle(document.querySelector('.model-code-chip')),local=getComputedStyle(document.querySelector('.local-chip'));return {overflow:document.documentElement.scrollWidth>innerWidth+1,shellWidth:shell.width,stageWidth:stage.width,gap:Math.round((shellNode.clientWidth-stage.width)*10)/10,gold:root.getPropertyValue('--gold').trim(),violet:root.getPropertyValue('--violet').trim(),scrollbarColor:root.scrollbarColor,scrollbarThumb:scroll.backgroundImage||scroll.backgroundColor,footerBackground:footer.backgroundImage,footerColor:footer.color,chipBackground:chip.backgroundColor,chipBorder:chip.borderColor,localBackground:local.backgroundColor,researchClosed:document.querySelector('#appShell').classList.contains('research-closed')};});
 assert.equal(errors.length,0,errors.join('\n'));assert.equal(layout.overflow,false,'page width '+width);assert.ok(Math.abs(layout.gap)<=1,`canvas gap ${layout.gap}px at ${width}`);assert.equal(layout.gold,'#e8bd55');assert.equal(layout.violet,'#62556e');assert.match(layout.scrollbarColor,/91, 77, 101/);assert.match(layout.chipBackground,/23, 19, 28/);assert.doesNotMatch(JSON.stringify(layout),/57, 68, 43|101, 117, 63|26, 28, 18|16, 19, 11/);
 if(width===1440){
  await page.locator('#researchVisibility').click();assert.equal(await page.locator('#appShell').evaluate(el=>el.classList.contains('research-closed')),true);assert.equal(await page.locator('#researchVisibility').getAttribute('aria-label'),'Show Research Desk');await page.locator('#researchVisibility').click();
  await page.locator('#resizeHandle').focus();await page.keyboard.press('Shift+ArrowLeft');assert.equal(await page.locator('#resizeHandle').getAttribute('aria-valuenow'),'410');await page.locator('#leftResizeHandle').focus();await page.keyboard.press('Shift+ArrowRight');assert.equal(await page.locator('#leftResizeHandle').getAttribute('aria-valuenow'),'325');
  await page.locator('#toggleResearch').click();await page.screenshot({path:`${directory}/view-options-1440.png`});await page.keyboard.press('Escape');
  await page.locator('#prompt').fill('Controlled private browser acceptance');await page.locator('#saveSession').click();await page.locator('#sessionNameInput').fill('Browser acceptance');await page.locator('#sessionConfirm').click();await page.getByText('Project and research saved to your account.',{exact:true}).waitFor();await page.reload();await page.waitForFunction(()=>document.body.dataset.ready==='true');assert.equal(await page.locator('#prompt').inputValue(),'Controlled private browser acceptance');
  const canvasFixtures=await page.evaluate(async()=>{const projectId=document.querySelector('[data-doc]').dataset.doc,items=[['Portrait fixture',120,240,false],['Square fixture',200,200,false],['Landscape fixture',320,120,true],['Ultra-wide fixture',640,100,false]],saved=[];for(const [title,width,height,transparent] of items){const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d');ctx.fillStyle=transparent?'rgba(98,85,110,.42)':'#211a28';ctx.fillRect(0,0,width,height);const response=await fetch('/api/import',{method:'POST',headers:{'Content-Type':'application/json','X-Lab-CSRF':'local-browser-fixture-csrf','X-Lab-Account':'local-browser-fixture'},body:JSON.stringify({projectId,title,dataUrl:canvas.toDataURL('image/png')})});if(!response.ok)throw new Error(await response.text());saved.push({title,width,height,transparent});}return saved;});
  for(const fixture of canvasFixtures){await page.locator('#libraryButton').click();await page.locator('.asset-tile').filter({hasText:fixture.title}).first().click();await page.waitForFunction(({width,height})=>{const img=document.querySelector('#resultImage');return !img.hidden&&img.naturalWidth===width&&img.naturalHeight===height;},fixture);const measured=await page.locator('#resultImage').evaluate(img=>{const image=img.getBoundingClientRect(),stage=document.querySelector('#stage').getBoundingClientRect();return {width:img.naturalWidth,height:img.naturalHeight,ratio:image.width/image.height,centerX:Math.abs((image.left+image.width/2)-(stage.left+stage.width/2)),centerY:Math.abs((image.top+image.height/2)-(stage.top+stage.height/2))};});assert.equal(measured.width,fixture.width);assert.equal(measured.height,fixture.height);assert.ok(Math.abs(measured.ratio-fixture.width/fixture.height)<.01);assert.ok(measured.centerX<=1&&measured.centerY<=1);}
  await page.locator('#imagesTab').click();await page.locator('#googleQuery').fill('gold violet studio');await page.locator('#imageFilters summary').click();await page.locator('#googleType').selectOption('photo');await page.locator('#googleDominant').selectOption('purple');await page.locator('#googleSearch').click();await page.locator('.gsc-imageResult .lab-google-actions').waitFor();assert.equal(await page.locator('.gsc-imageResult').count(),1);assert.match(await page.locator('#googleExternal').getAttribute('href'),/^https:\/\/www\.google\.com\/search/);assert.equal(await page.getByText('Enhanced by Google',{exact:true}).count(),1);await page.screenshot({path:`${directory}/google-images-1440.png`,fullPage:true});
  await page.locator('.gsc-imageResult [data-image-action="chat"]').click();await page.locator('#toast').waitFor({state:'visible'});assert.equal(await page.locator('#toast').textContent(),'Image added to the Research draft. It was not sent.');await page.locator('#chatTab').click();assert.equal(await page.locator('#chatAttachments img').count(),1);await page.locator('#imagesTab').click();
  const incompatibleModel=await page.locator('#modelName').textContent();await page.locator('[data-image-action="generator"]').click();await page.getByText(/active model has no compatible image input/).waitFor();assert.equal(await page.locator('#studioAttachments img').count(),1);assert.equal(await page.locator('#modelName').textContent(),incompatibleModel);await page.locator('#imagesTab').click();
  await page.locator('#modelPicker').click();await page.locator('#modelQuery').fill('fixture/single-image');await page.locator('#searchModels').click();await page.locator('#modelsDialog').waitFor({state:'hidden'});await page.locator('#imagesTab').click();await page.locator('[data-image-action="generator"]').click();await page.locator('[data-preview="image"] img').waitFor();assert.equal(await page.locator('[data-preview="image"] img').count(),1);await page.locator('#imagesTab').click();
  await page.locator('#modelPicker').click();await page.locator('#modelQuery').fill('fixture/multi-image');await page.locator('#searchModels').click();await page.locator('#modelsDialog').waitFor({state:'hidden'});await page.locator('#imagesTab').click();await page.locator('[data-image-action="generator"]').click();await page.locator('#imageResultTargetDialog').waitFor({state:'visible'});assert.equal(await page.locator('#imageResultTargetList [data-result-target]').count(),2);await page.screenshot({path:`${directory}/image-target-chooser-1440.png`});await page.locator('#imageResultTargetList [data-result-target="image"]').click();await page.locator('[data-preview="image"] img').waitFor();await page.locator('#imagesTab').click();
  await page.locator('[data-image-action="compose"]').click();await page.locator('#sessionDialog').waitFor({state:'visible'});assert.equal(await page.locator('#sessionConfirm').textContent(),'Replace image');assert.equal(await page.locator('#resultImage').evaluate(img=>img.naturalWidth),640);await page.locator('#sessionConfirm').click();await page.waitForFunction(()=>document.body.classList.contains('thumbnail-mode'));assert.match(await page.locator('#toast').evaluate(el=>getComputedStyle(el).backgroundColor),/36, 32, 42/);await page.screenshot({path:`${directory}/compose-import-1440.png`,fullPage:true});
  await page.locator('#stockTab').click();await page.locator('#stockQuery').fill('violet studio');await page.locator('#stockSearch').click();await page.locator('.stock-result-card').waitFor();assert.equal(await page.locator('.stock-result-card').count(),1);assert.match(await page.locator('.stock-result-copy').textContent(),/Workshop Artist.*Pexels/s);await page.screenshot({path:`${directory}/stock-pexels-1440.png`,fullPage:true});await page.locator('[data-stock-provider="pixabay"]').click();await page.locator('#stockSearch').click();await page.locator('.stock-result-copy').filter({hasText:'Pixabay'}).waitFor();assert.match(await page.locator('.stock-result-copy').textContent(),/Workshop.*Pixabay/s);await page.screenshot({path:`${directory}/stock-pixabay-1440.png`,fullPage:true});
  await page.locator('#fullScreen').click();await page.waitForFunction(()=>Boolean(document.fullscreenElement));await page.screenshot({path:`${directory}/canvas-fullscreen-1440.png`});await page.evaluate(()=>document.exitFullscreen());await page.waitForFunction(()=>!document.fullscreenElement);
  await page.locator('#imagesTab').click();const popupPromise=context.waitForEvent('page');await page.locator('#popoutResearch').click();const popup=await popupPromise;await popup.waitForLoadState();assert.match(popup.url(),/\/research\?session=.*&tab=images/);await popup.screenshot({path:`${directory}/research-popout.png`});await popup.close();
  await page.locator('#accountTrigger').click();await page.screenshot({path:`${directory}/account-1440.png`});await page.locator('#accountTrigger').click();await page.locator('#connections').click();await page.screenshot({path:`${directory}/connections-top-1440.png`});await page.locator('#settingsDialog .dialog-body').evaluate(el=>el.scrollTop=el.scrollHeight);await page.screenshot({path:`${directory}/connections-scrolled-1440.png`});await page.locator('#settingsDialog .dialog-head button').click();await page.locator('#settingsPageButton').click();await page.locator('#usageKpis').waitFor();await page.screenshot({path:`${directory}/settings-1440.png`,fullPage:true});await page.locator('#brandPageButton').click();await page.screenshot({path:`${directory}/brand-1440.png`,fullPage:true});await page.locator('#libraryButton').click();await page.screenshot({path:`${directory}/library-1440.png`,fullPage:true});
 }
 if(width!==1440){
  if(width<=1000)await page.locator('#researchVisibility').evaluate(element=>{element.style.display='flex';});
  if(width<=1000)await page.locator('#researchVisibility').click();await page.locator('#imagesTab').click();await page.locator('#googleQuery').fill('gold violet studio');await page.locator('#googleSearch').click();await page.locator('.gsc-imageResult .lab-google-actions').waitFor();await page.screenshot({path:`${directory}/google-images-${width}.png`,fullPage:true});await page.locator('#stockTab').click();await page.locator('#stockQuery').fill('violet studio');await page.locator('#stockSearch').click();await page.locator('.stock-result-card').waitFor();await page.screenshot({path:`${directory}/stock-pexels-${width}.png`,fullPage:true});await page.locator('[data-stock-provider="pixabay"]').click();await page.locator('#stockSearch').click();await page.locator('.stock-result-copy').filter({hasText:'Pixabay'}).waitFor();await page.screenshot({path:`${directory}/stock-pixabay-${width}.png`,fullPage:true});await page.locator('#connections').click();await page.screenshot({path:`${directory}/connections-top-${width}.png`});await page.locator('#settingsDialog .dialog-body').evaluate(el=>el.scrollTop=el.scrollHeight);await page.screenshot({path:`${directory}/connections-scrolled-${width}.png`});await page.locator('#settingsDialog .dialog-head button').click();await page.locator('#settingsPageButton').click();await page.locator('#usageKpis').waitFor();await page.screenshot({path:`${directory}/settings-${width}.png`,fullPage:true});
 }
 const unexpectedErrors=errors.filter(error=>!/^503 .*\/api\/provider-models\?provider=xai&kind=(image|chat)$/.test(error));assert.equal(unexpectedErrors.length,0,unexpectedErrors.join('\n'));evidence.push({width,height,headed,errors:unexpectedErrors,horizontalOverflow:false,canvasGap:layout.gap,researchClosedAtMobile:width<=1000?layout.researchClosed:null});await context.close();
}await writeFile(directory+'/checks.json',JSON.stringify(evidence,null,2));console.log(JSON.stringify({directory,evidence}));}finally{await browser.close();}
