import {chromium} from '../../ThirdRailify/node_modules/playwright-core/index.mjs';
import {mkdir,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const directory='X:/GIT/ThirdRailify-Lab/.artifacts/browser/gold-violet-'+Date.now();await mkdir(directory,{recursive:true});
const headed=process.env.LAB_BROWSER_HEADED==='1';
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:!headed});
const evidence=[];
const googleElementFixture=`(()=>{const elements={};window.google={search:{cse:{element:{render(o){const host=document.getElementById(o.div),control=document.createElement('div'),results=document.createElement('div');control.className='gsc-control-cse';results.className='gsc-results';control.append(results);host.replaceChildren(control);elements[o.gname]={execute(query){const cb=window.__gcse.searchCallbacks.image;query=cb.starting(o.gname,query);if(query==='provider challenge')return;const deliver=()=>{const result={title:'<img src=x onerror="window.__googleInjected=true">',titleNoFormatting:'Gold violet studio reference',url:'https://fixture.images.example/reference.png',visibleUrl:'fixture.example/reference',contextUrl:'https://fixture.example/reference',image:{url:'https://fixture.images.example/reference.png',width:1200,height:800},thumbnailImage:{url:query==='thumbnail failure'?'https://fixture.images.example/missing.png':'https://fixture.images.example/reference.png',width:300,height:200},fileFormat:'image/png'};const promo={title:'Workshop promotion',content:'Required promotional content',url:'https://fixture.example/promotion',visibleUrl:'fixture.example',image:{url:'https://fixture.images.example/reference.png',width:300,height:200}};const rawResults=query==='no results'?[]:query==='malformed result'?[{}]:query==='callback failure'?null:[result],rawPromos=query==='callback failure'?null:[promo];const handled=cb.ready(o.gname,query,rawPromos,rawResults,results);if(handled!==true)(0,eval)("results.textContent='DEFAULT GOOGLE RENDERER'");const branding=document.createElement('div');branding.className='gsc-branding';branding.textContent='Enhanced by Google';control.querySelector('.gsc-branding')?.remove();control.append(branding);cb.rendered(o.gname,query,[],[]);};if(query==='late project result')setTimeout(deliver,120);else deliver();}};},getElement(name){return elements[name];}}}}};window.__gcse.initializationCallback();})();`;
async function verifyUsage(page,width){
  await page.route('**/api/usage?*',route=>{
    const url=new URL(route.request().url()),range=url.searchParams.get('range'),empty=url.searchParams.get('provider')==='unsplash';
    const make=(hours,requests)=>({bucket:new Date(Date.now()-hours*3600000).toISOString(),requests,tokens:requests*1250,outputs:requests,searches:requests-1,tool_calls:1,actual_ticks:requests*4800000,estimated_nanos:requests*3000000,unknown_count:0,breakdown:[{provider:'xai',model:'grok-4.6',requests,tokens:requests*1250,outputs:requests,searches:0,tool_calls:1,actual_ticks:requests*4800000,estimated_nanos:0}]});
    const series=empty?[]:range==='24h'?[make(4,1),make(2,2),make(0,3)]:range==='7d'?[make(24,2),make(0,4)]:[make(0,6)];
    const base={provider:'xai',model:'grok-latest',served_model:'grok-4.6',operation:'research_chat',outcome:'succeeded',input_tokens:7000,output_tokens:500,tool_calls:1,started_at:new Date().toISOString()};
    const recent=empty?[]:[
      {...base,cost_basis:'actual_provider',actual_cost_ticks:28800000,coverage_reason:'Exact provider-reported xAI request cost.',calculation_text:'28,800,000 provider ticks / 10,000,000,000 ticks/USD'},
      {...base,provider:'replicate',model:'black-forest-labs/flux-schnell',served_model:null,operation:'image_generation',cost_basis:'estimated_catalog',estimated_cost_nanos:3000000,generated_outputs:1,coverage_reason:'Complete estimate from a versioned official pricing entry.',calculation_text:'1 output x $0.003/image',pricing_rate_id:'replicate-flux-schnell-output-2026-09-13',pricing_snapshot_json:JSON.stringify({sourceUrl:'https://replicate.com/black-forest-labs/flux-schnell/api/schema',effectiveFrom:'2024-08-01'})},
      {...base,provider:'replicate',model:'owner/unpriced',served_model:null,outcome:'failed',cost_basis:'unknown',coverage_reason:'Estimate unavailable.'},
      {...base,provider:'openai',model:null,served_model:null,operation:'model_discovery',outcome:'processing',cost_basis:'not_applicable',coverage_reason:'Provider catalogue lookup; not an inference operation.'},
      {...base,provider:'pexels',model:null,served_model:null,operation:'stock_search',input_tokens:0,output_tokens:0,tool_calls:0,search_count:1,cost_basis:'free_or_nonbillable_when_proven',coverage_reason:'Configured free stock API tier.'},
    ];
    const providers=empty?[]:[
      {provider:'xai',requests:6,tokens:7500,actual_ticks:28800000,estimated_nanos:0,actual_count:1,estimated_count:0},
      {provider:'pexels',requests:1,tokens:0,rate_limit:25000,rate_remaining:24999,actual_count:0,estimated_count:0},
      {provider:'pixabay',requests:2,tokens:0,rate_limit:100,rate_remaining:5,actual_count:0,estimated_count:0},
      {provider:'unsplash',requests:2,tokens:0,rate_limit:50,rate_remaining:10,actual_count:0,estimated_count:0},
    ];
    route.fulfill({contentType:'application/json',body:JSON.stringify({range,bucketSeconds:range==='24h'?3600:86400,summary:{requests:6,tokens:7500,outputs:6,searches:5,tool_calls:1,actual_ticks:28800000,estimated_nanos:18000000,actual_count:1,estimated_count:1,unknown_count:0,pricing_coverage_percent:100},series,providers,recent})});
  });
  await Promise.all([page.waitForResponse(response=>response.url().includes('/api/usage?range=7d')),page.locator('#usageRange').selectOption('7d')]);await page.waitForFunction(()=>document.querySelector('#usageChart svg')?.getAttribute('aria-label')?.includes('2 real data points'));assert.equal(await page.locator('#usageChart .usage-point').count(),2);await Promise.all([page.waitForResponse(response=>response.url().includes('/api/usage?range=30d')),page.locator('#usageRange').selectOption('30d')]);await page.waitForFunction(()=>document.querySelector('#usageChart svg')?.getAttribute('aria-label')?.includes('1 real data point'));
  assert.equal(await page.locator('#usageMetric option').count(),8);assert.ok(await page.locator('#usageRecent .provider-logo').count()>0);for(const label of ['ACTUAL','EST.','UNKNOWN','NOT APPLICABLE','FREE / NON-BILLABLE'])assert.ok((await page.locator('#usageRecent').textContent()).includes(label));assert.equal(await page.locator('#usageChart .usage-point').count(),1);assert.equal(await page.locator('#usageChart .usage-line').count(),0);
  assert.equal(await page.locator('#usageRecent .usage-outcome.success').count(),3);assert.equal(await page.locator('#usageRecent .usage-outcome.danger').count(),1);assert.equal(await page.locator('#usageRecent .usage-outcome.warning').count(),1);assert.match(await page.locator('#usageRecent').textContent(),/US\$0\.00288|US\$0\.003/);assert.match(await page.locator('#usageProviders').textContent(),/24,999 of 25,000 reported remaining/);
  const pexelsQuota=page.locator('[role="progressbar"][aria-label^="Pexels"]');assert.equal(await pexelsQuota.getAttribute('aria-valuenow'),'1');assert.equal(await pexelsQuota.getAttribute('aria-valuemax'),'25000');
  assert.equal(await page.locator('.usage-quota.warning').count(),1);assert.equal(await page.locator('.usage-quota.danger').count(),1);assert.match(await page.locator('.usage-quota.warning [role="progressbar"]').getAttribute('aria-label'),/approaching quota limit/);assert.match(await page.locator('.usage-quota.danger [role="progressbar"]').getAttribute('aria-label'),/critical quota usage/);
  await page.locator('[data-usage-sort="provider"]').click();assert.equal(await page.locator('[data-usage-column="provider"]').getAttribute('aria-sort'),'ascending');assert.match(await page.locator('#usageRecent tbody tr').first().textContent(),/Grok \/ xAI/);await page.locator('[data-usage-sort="provider"]').click();assert.equal(await page.locator('[data-usage-column="provider"]').getAttribute('aria-sort'),'descending');assert.match(await page.locator('#usageRecent tbody tr').first().textContent(),/Replicate/);
  const resizeHandle=page.locator('[data-usage-resize="provider"]');if(width>700){const before=Number(await resizeHandle.getAttribute('aria-valuenow')),box=await resizeHandle.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+28,box.y+box.height/2);await page.mouse.up();assert.ok(Number(await resizeHandle.getAttribute('aria-valuenow'))>=before+26);}else assert.equal(await resizeHandle.evaluate(element=>getComputedStyle(element).display),'none');
  await Promise.all([page.waitForResponse(response=>response.url().includes('/api/usage?range=24h')),page.locator('#usageRange').selectOption('24h')]);await page.locator('#usageChart .usage-line').waitFor();assert.ok(await page.locator('#usageChart .usage-point').count()>=2);
  for(const [metric,label] of [['requests','Requests'],['tokens','Tokens'],['outputs','Outputs'],['searches','Searches'],['tool_calls','Tool calls'],['actual_ticks','Actual provider cost'],['estimated_nanos','Estimated cost'],['observed_cost','Observed cost']]){await page.locator('#usageMetric').selectOption(metric);await page.waitForFunction(expected=>document.querySelector('#usageChart .usage-chart-head')?.textContent.includes(expected),label);}
  await page.locator('#usageMetric').selectOption('actual_ticks');await page.waitForFunction(()=>document.querySelector('#usageChart .usage-chart-head')?.textContent.includes('Actual provider cost'));await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.locator('#usageChart .usage-line').evaluate(element=>getComputedStyle(element).animationName),'none');await page.emulateMedia({reducedMotion:'no-preference'});
  await page.locator('#usageProvider').selectOption('unsplash');await page.locator('#usageChart .usage-chart-empty').waitFor();assert.match(await page.locator('#usageChart').textContent(),/No recorded operations/);await page.locator('#usageProvider').selectOption('');await page.locator('#usageRange').selectOption('30d');await page.locator('#usageMetric').selectOption('requests');await page.locator('#usageChart .usage-point').waitFor();await page.locator('.usage-card').scrollIntoViewIfNeeded();await page.waitForTimeout(1000);await page.screenshot({path:`${directory}/settings-usage-${width}.png`});
}
try{for(const [width,height]of [[1920,1080],[1440,900],[768,1024],[390,844]]){
 const context=await browser.newContext({viewport:{width,height}});await context.addCookies([{name:'thirdrailify_session',value:'local-browser-fixture-token-12345678901234567890',url:'http://127.0.0.1:8798',httpOnly:true,sameSite:'Lax'}]);await context.route('https://fixture.example/**',route=>route.fulfill({contentType:'text/html',body:'<!doctype html><title>Fixture source</title>'}));const page=await context.newPage(),errors=[];await page.route('https://cse.google.com/cse.js**',route=>route.fulfill({contentType:'text/javascript',body:googleElementFixture}));await page.route('https://fixture.images.example/**',route=>route.request().url().endsWith('/missing.png')?route.fulfill({status:404}):route.fulfill({contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=','base64')}));page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=500)errors.push(`${r.status()} ${r.url()}`);});page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('Failed to load resource'))errors.push(m.text());});
 await page.goto('http://127.0.0.1:8798/');await page.waitForFunction(()=>document.body.dataset.ready==='true');await page.locator('#accountTrigger').filter({hasText:'Workshop Test'}).waitFor();await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:`${directory}/studio-${width}.png`,fullPage:true});
 const layout=await page.evaluate(()=>{const shellNode=document.querySelector('#stageShell'),shell=shellNode.getBoundingClientRect(),stage=document.querySelector('#stage').getBoundingClientRect(),root=getComputedStyle(document.documentElement),scroll=getComputedStyle(document.documentElement,'::-webkit-scrollbar-thumb'),footer=getComputedStyle(document.querySelector('.statusbar')),chip=getComputedStyle(document.querySelector('.model-code-chip')),local=getComputedStyle(document.querySelector('.local-chip'));return {overflow:document.documentElement.scrollWidth>innerWidth+1,shellWidth:shell.width,stageWidth:stage.width,gap:Math.round((shellNode.clientWidth-stage.width)*10)/10,gold:root.getPropertyValue('--gold').trim(),violet:root.getPropertyValue('--violet').trim(),scrollbarColor:root.scrollbarColor,scrollbarThumb:scroll.backgroundImage||scroll.backgroundColor,footerBackground:footer.backgroundImage,footerColor:footer.color,chipBackground:chip.backgroundColor,chipBorder:chip.borderColor,localBackground:local.backgroundColor,researchClosed:document.querySelector('#appShell').classList.contains('research-closed')};});
 assert.equal(errors.length,0,errors.join('\n'));assert.equal(layout.overflow,false,'page width '+width);assert.ok(Math.abs(layout.gap)<=1,`canvas gap ${layout.gap}px at ${width}`);assert.equal(layout.gold,'#e8bd55');assert.equal(layout.violet,'#62556e');assert.match(layout.scrollbarColor,/91, 77, 101/);assert.match(layout.chipBackground,/23, 19, 28/);assert.doesNotMatch(JSON.stringify(layout),/57, 68, 43|101, 117, 63|26, 28, 18|16, 19, 11/);
 if(width===1440){
  await page.locator('#researchVisibility').click();assert.equal(await page.locator('#appShell').evaluate(el=>el.classList.contains('research-closed')),true);assert.equal(await page.locator('#researchVisibility').getAttribute('aria-label'),'Show Research Desk');await page.locator('#researchVisibility').click();
  await page.locator('#resizeHandle').focus();await page.keyboard.press('Shift+ArrowLeft');assert.equal(await page.locator('#resizeHandle').getAttribute('aria-valuenow'),'410');await page.locator('#leftResizeHandle').focus();await page.keyboard.press('Shift+ArrowRight');assert.equal(await page.locator('#leftResizeHandle').getAttribute('aria-valuenow'),'325');
  await page.locator('#toggleResearch').click();await page.screenshot({path:`${directory}/view-options-1440.png`});await page.keyboard.press('Escape');
  await page.locator('#prompt').fill('Controlled private browser acceptance');await page.locator('#saveSession').click();await page.locator('#sessionNameInput').fill('Browser acceptance');await page.locator('#sessionConfirm').click();await page.getByText('Project and research saved to your account.',{exact:true}).waitFor();await page.reload();await page.waitForFunction(()=>document.body.dataset.ready==='true');assert.equal(await page.locator('#prompt').inputValue(),'Controlled private browser acceptance');
  const canvasFixtures=await page.evaluate(async()=>{const projectId=document.querySelector('[data-doc]').dataset.doc,items=[['Portrait fixture',120,240,false],['Square fixture',200,200,false],['Landscape fixture',320,120,true],['Ultra-wide fixture',640,100,false]],saved=[];for(const [title,width,height,transparent] of items){const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d');ctx.fillStyle=transparent?'rgba(98,85,110,.42)':'#211a28';ctx.fillRect(0,0,width,height);const response=await fetch('/api/import',{method:'POST',headers:{'Content-Type':'application/json','X-Lab-CSRF':'local-browser-fixture-csrf','X-Lab-Account':'local-browser-fixture'},body:JSON.stringify({projectId,title,dataUrl:canvas.toDataURL('image/png')})});if(!response.ok)throw new Error(await response.text());saved.push({title,width,height,transparent});}return saved;});
  for(const fixture of canvasFixtures){await page.locator('#libraryButton').click();await page.locator('.asset-tile').filter({hasText:fixture.title}).first().click();await page.waitForFunction(({width,height})=>{const img=document.querySelector('#resultImage');return !img.hidden&&img.naturalWidth===width&&img.naturalHeight===height;},fixture);const measured=await page.locator('#resultImage').evaluate(img=>{const image=img.getBoundingClientRect(),stage=document.querySelector('#stage').getBoundingClientRect();return {width:img.naturalWidth,height:img.naturalHeight,ratio:image.width/image.height,centerX:Math.abs((image.left+image.width/2)-(stage.left+stage.width/2)),centerY:Math.abs((image.top+image.height/2)-(stage.top+stage.height/2))};});assert.equal(measured.width,fixture.width);assert.equal(measured.height,fixture.height);assert.ok(Math.abs(measured.ratio-fixture.width/fixture.height)<.01);assert.ok(measured.centerX<=1&&measured.centerY<=1);}
  await page.locator('#imagesTab').click();await page.locator('#googleQuery').fill('gold violet studio');await page.locator('#imageFilters summary').click();await page.locator('#googleType').selectOption('photo');await page.locator('#googleDominant').selectOption('purple');await page.locator('#googleSearch').click();await page.locator('.google-image-result .google-result-actions').waitFor();assert.equal(await page.locator('.google-image-result').count(),1);assert.equal(await page.locator('.google-promotions .google-promotion-card').count(),1);assert.equal(await page.locator('.google-image-result img').evaluate(image=>image.complete&&image.naturalWidth>0),true);assert.equal(await page.evaluate(()=>window.__googleInjected),undefined);assert.equal(await page.getByText('DEFAULT GOOGLE RENDERER',{exact:true}).count(),0);assert.match(await page.locator('#googleExternal').getAttribute('href'),/^https:\/\/www\.google\.com\/search/);assert.equal(await page.getByText('Enhanced by Google',{exact:true}).count(),1);assert.deepEqual(await page.locator('.google-result-actions').getByRole('button').allTextContents(),['ADD TO CHAT','REFERENCE','COMPOSE']);assert.equal(await page.locator('.google-result-actions').getByRole('link',{name:'SOURCE'}).count(),1);await page.screenshot({path:`${directory}/google-images-1440.png`,fullPage:true});
  const sourcePopupPromise=context.waitForEvent('page');await page.locator('.google-result-actions').getByRole('link',{name:'SOURCE'}).click();const sourcePopup=await sourcePopupPromise;await sourcePopup.waitForLoadState();assert.equal(sourcePopup.url(),'https://fixture.example/reference');await sourcePopup.close();
  await page.locator('.google-image-result [data-image-action="chat"]').click();await page.locator('#toast').waitFor({state:'visible'});assert.equal(await page.locator('#toast').textContent(),'Image added to the Research draft. It was not sent.');await page.locator('#chatTab').click();assert.equal(await page.locator('#chatAttachments img').count(),1);await page.locator('#imagesTab').click();
  const incompatibleModel=await page.locator('#modelName').textContent();await page.locator('[data-image-action="generator"]').click();await page.getByText(/active model has no compatible image input/).waitFor();assert.equal(await page.locator('#studioAttachments img').count(),1);assert.equal(await page.locator('#modelName').textContent(),incompatibleModel);await page.locator('#imagesTab').click();
  await page.locator('#modelPicker').click();await page.locator('#modelQuery').fill('fixture/single-image');await page.locator('#searchModels').click();await page.locator('#modelsDialog').waitFor({state:'hidden'});await page.locator('#imagesTab').click();await page.locator('[data-image-action="generator"]').click();await page.locator('[data-preview="image"] img').waitFor();assert.equal(await page.locator('[data-preview="image"] img').count(),1);await page.locator('#imagesTab').click();
  await page.locator('#modelPicker').click();await page.locator('#modelQuery').fill('fixture/multi-image');await page.locator('#searchModels').click();await page.locator('#modelsDialog').waitFor({state:'hidden'});await page.locator('#imagesTab').click();await page.locator('[data-image-action="generator"]').click();await page.locator('#imageResultTargetDialog').waitFor({state:'visible'});assert.equal(await page.locator('#imageResultTargetList [data-result-target]').count(),2);await page.screenshot({path:`${directory}/image-target-chooser-1440.png`});await page.locator('#imageResultTargetList [data-result-target="image"]').click();await page.locator('[data-preview="image"] img').waitFor();await page.locator('#imagesTab').click();
  await page.locator('[data-image-action="compose"]').click();await page.locator('#sessionDialog').waitFor({state:'visible'});assert.equal(await page.locator('#sessionConfirm').textContent(),'Replace image');assert.equal(await page.locator('#resultImage').evaluate(img=>img.naturalWidth),640);await page.locator('#sessionConfirm').click();await page.waitForFunction(()=>document.body.classList.contains('thumbnail-mode'));assert.match(await page.locator('#toast').evaluate(el=>getComputedStyle(el).backgroundColor),/36, 32, 42/);await page.screenshot({path:`${directory}/compose-import-1440.png`,fullPage:true});
  for(const [query,expected] of [['no results','No image results.'],['malformed result','Google results could not be displayed.'],['callback failure','Google Images could not display these results.']]){await page.locator('#imagesTab').click();await page.locator('#googleQuery').fill(query);await page.locator('#googleSearch').click();await page.getByText(expected,{exact:true}).waitFor();assert.equal(await page.locator('#googleSearchState').textContent().then(value=>value.includes('EvalError')),false);}
  await page.locator('#googleQuery').fill('thumbnail failure');await page.locator('#googleSearch').click();await page.locator('.google-image-result img').waitFor();await page.waitForFunction(()=>document.querySelector('.google-image-result img')?.src.endsWith('/reference.png'));assert.equal(await page.locator('.google-image-result img').evaluate(image=>image.complete&&image.naturalWidth>0),true);
  await page.locator('#googleQuery').fill('provider challenge');await page.locator('#googleSearch').click();await page.getByText('Google Images took too long.',{exact:true}).waitFor({timeout:17000});assert.match(await page.locator('#googleSearchState').textContent(),/provider challenge/);
  await page.locator('#googleQuery').fill('late project result');await page.locator('#googleSearch').click();const originatingProject=await page.locator('.document-tab.active').getAttribute('data-doc');await page.locator('#libraryButton').click();await page.locator('#libraryNew').click();await page.waitForFunction(project=>document.querySelector('.document-tab.active')?.dataset.doc!==project,originatingProject);await page.waitForTimeout(250);await page.locator('#imagesTab').click();assert.equal(await page.locator('.google-image-result').count(),0);assert.match(await page.locator('#googleSearchState').textContent(),/reference shelf/);
  await page.locator('#stockTab').click();await page.locator('#stockQuery').fill('violet studio');await page.locator('#stockSearch').click();await page.locator('.stock-result-card').waitFor();assert.equal(await page.locator('.stock-result-card').count(),1);assert.match(await page.locator('.stock-result-copy').textContent(),/Workshop Artist.*Pexels/s);await page.screenshot({path:`${directory}/stock-pexels-1440.png`,fullPage:true});await page.locator('[data-stock-provider="pixabay"]').click();await page.locator('#stockSearch').click();await page.locator('.stock-result-copy').filter({hasText:'Pixabay'}).waitFor();assert.match(await page.locator('.stock-result-copy').textContent(),/Workshop.*Pixabay/s);await page.screenshot({path:`${directory}/stock-pixabay-1440.png`,fullPage:true});
  await page.locator('#fullScreen').click();await page.waitForFunction(()=>Boolean(document.fullscreenElement));await page.screenshot({path:`${directory}/canvas-fullscreen-1440.png`});await page.evaluate(()=>document.exitFullscreen());await page.waitForFunction(()=>!document.fullscreenElement);
  await page.locator('#imagesTab').click();const popupPromise=context.waitForEvent('page');await page.locator('#popoutResearch').click();const popup=await popupPromise;await popup.waitForLoadState();assert.match(popup.url(),/\/research\?session=.*&tab=images/);await popup.screenshot({path:`${directory}/research-popout.png`});await popup.close();
  await page.locator('#accountTrigger').click();await page.screenshot({path:`${directory}/account-1440.png`});await page.locator('#accountTrigger').click();await page.locator('#connections').click();await page.screenshot({path:`${directory}/connections-top-1440.png`});await page.locator('#settingsDialog .dialog-body').evaluate(el=>el.scrollTop=el.scrollHeight);await page.screenshot({path:`${directory}/connections-scrolled-1440.png`});await page.locator('#settingsDialog .dialog-head button').click();await page.locator('#settingsPageButton').click();await page.locator('#usageKpis').waitFor();await verifyUsage(page,width);await page.screenshot({path:`${directory}/settings-1440.png`,fullPage:true});await page.locator('#brandPageButton').click();await page.screenshot({path:`${directory}/brand-1440.png`,fullPage:true});await page.locator('#libraryButton').click();await page.screenshot({path:`${directory}/library-1440.png`,fullPage:true});
 }
 if(width!==1440){
  if(width<=1000)await page.locator('#researchVisibility').evaluate(element=>{element.style.display='flex';});
  if(width<=1000)await page.locator('#researchVisibility').click();await page.locator('#imagesTab').click();await page.locator('#googleQuery').fill('gold violet studio');await page.locator('#googleSearch').click();await page.locator('.google-image-result .google-result-actions').waitFor();assert.equal(await page.locator('.google-image-result img').evaluate(image=>image.complete&&image.naturalWidth>0),true);await page.screenshot({path:`${directory}/google-images-${width}.png`,fullPage:true});await page.locator('#stockTab').click();await page.locator('#stockQuery').fill('violet studio');await page.locator('#stockSearch').click();await page.locator('.stock-result-card').waitFor();assert.equal(await page.locator('.stock-result-card img').evaluate(image=>image.complete&&image.naturalWidth>0),true);await page.screenshot({path:`${directory}/stock-pexels-${width}.png`,fullPage:true});await page.locator('[data-stock-provider="pixabay"]').click();await page.locator('#stockSearch').click();await page.locator('.stock-result-copy').filter({hasText:'Pixabay'}).waitFor();await page.screenshot({path:`${directory}/stock-pixabay-${width}.png`,fullPage:true});await page.locator('#connections').click();await page.screenshot({path:`${directory}/connections-top-${width}.png`});await page.locator('#settingsDialog .dialog-body').evaluate(el=>el.scrollTop=el.scrollHeight);await page.screenshot({path:`${directory}/connections-scrolled-${width}.png`});await page.locator('#settingsDialog .dialog-head button').click();await page.locator('#settingsPageButton').click();await page.locator('#usageKpis').waitFor();await verifyUsage(page,width);await page.screenshot({path:`${directory}/settings-${width}.png`,fullPage:true});
 }
 const unexpectedErrors=errors.filter(error=>!/^503 .*\/api\/provider-models\?provider=xai&kind=(image|chat)$/.test(error));assert.equal(unexpectedErrors.length,0,unexpectedErrors.join('\n'));evidence.push({width,height,headed,errors:unexpectedErrors,horizontalOverflow:false,canvasGap:layout.gap,researchClosedAtMobile:width<=1000?layout.researchClosed:null});await context.close();
}await writeFile(directory+'/checks.json',JSON.stringify(evidence,null,2));console.log(JSON.stringify({directory,evidence}));}finally{await browser.close();}
