'use strict';
const {test}=require('node:test');
const assert=require('node:assert/strict');
const M=require('../public/model.js');
function setup(){const b=M.board('Test');b.objects=[M.node('frame',{id:'a',x:100,y:200,w:500,h:500,title:'Parent'}),M.node('note',{id:'b',x:50,y:70,w:200,h:150,title:'Idea',text:'A conversation',tags:['episode'],fields:[{key:'duration',type:'number',value:12}],owner:'Gina'})];return b;}
test('seven-character case-sensitive base62 codes, 10,000 unique samples',()=>{const set=new Set();for(let i=0;i<10000;i++){const s=M.slug();assert.match(s,/^[a-zA-Z0-9]{7}$/);set.add(s);}assert.equal(set.size,10000);});
test('parenting and detaching preserve world position',()=>{const b=setup(),n=b.objects[1];const p=M.worldPosition(n,M.index(b));assert.equal(M.reparent(b,'b','a'),true);assert.deepEqual(M.worldPosition(n,M.index(b)),p);assert.equal(n.parentId,'a');M.reparent(b,'b',null);assert.deepEqual({x:n.x,y:n.y},p);});
test('moving a parent moves a child exactly once',()=>{const b=setup();M.reparent(b,'b','a');const before=M.worldPosition(b.objects[1],M.index(b));b.objects[0].x+=90;assert.equal(M.worldPosition(b.objects[1],M.index(b)).x,before.x+90);});
test('cycle and non-container parenting are rejected',()=>{const b=setup();b.objects.push(M.node('frame',{id:'nested'}));assert.equal(M.reparent(b,'nested','a'),true);assert.equal(M.canParent(b,'a','nested'),false);assert.equal(M.canParent(b,'a','a'),false);assert.equal(M.canParent(b,'a','b'),false);});
test('group and ungroup preserve child geometry',()=>{const b=setup(),pos=M.worldPosition(b.objects[1],M.index(b));const f=M.group(b,new Set(['b']));assert.equal(b.objects[1].parentId,f.id);assert.deepEqual(M.worldPosition(b.objects[1],M.index(b)),pos);M.ungroup(b,f.id);assert.deepEqual(M.worldPosition(b.objects[1],M.index(b)),pos);});
test('deleting a container removes descendants and bound connections',()=>{const b=setup();M.reparent(b,'b','a');b.edges.push({id:'edge',from:{nodeId:'b'},to:{x:1,y:2}});M.remove(b,['a']);assert.equal(b.objects.length,0);assert.equal(b.edges.length,0);});
test('search finds text, tags, assignments and typed metadata',()=>{const b=setup();for(const q of ['conversation','episode','GINA','duration','12'])assert.equal(M.search(b,q)[0].id,'b');assert.equal(M.search(b,'unmatched').length,0);});
test('field-level patches preserve unrelated concurrent edits',()=>{const b=setup(),first=M.clone(b),second=M.clone(b);first.objects[1].title='New title';second.objects[1].x=900;M.apply(b,M.diff(b,first));const base=setup();M.apply(b,M.diff(base,second));assert.equal(b.objects[1].title,'New title');assert.equal(b.objects[1].x,900);});
test('stacking order is part of the persisted command',()=>{const b=setup(),after=M.clone(b);after.objects.reverse();const c=M.diff(b,after);M.apply(b,c);assert.equal(b.objects[0].id,'b');});
test('import rejects duplicate object IDs and hierarchy cycles',()=>{const b=setup();b.objects.push(M.clone(b.objects[1]));assert.throws(()=>M.validate(b),/duplicate/);const c=setup();c.objects.push(M.node('frame',{id:'nested',parentId:'a'}));c.objects[0].parentId='nested';assert.throws(()=>M.validate(c),/hierarchy/);});
test('import enforces format and node-count limits',()=>{assert.throws(()=>M.validate({schemaVersion:99,objects:[],edges:[]}),/version/);const b=setup();b.objects=Array.from({length:1501},()=>M.node('note'));assert.throws(()=>M.validate(b),/1,500/);});
test('remote media requires HTTPS without credentials and denies local addresses',()=>{for(const u of ['javascript:alert(1)','http://example.com/a.png','https://x:y@example.com/a.png','https://127.0.0.1/a','https://10.1.1.1/a','https://172.16.0.2/a','https://192.168.1.1/a','https://localhost/a'])assert.equal(M.safeURL(u),null);assert.equal(M.safeURL('https://example.com/a.gif'),'https://example.com/a.gif');});
test('typed fields are data, never executable expressions',()=>{const b=setup();b.objects[1].fields=[{key:'formula',type:'text',value:'=alert(1)'},{key:'flag',type:'boolean',value:true}];const normalized=M.validate(b);assert.equal(normalized.objects[1].fields[0].value,'=alert(1)');assert.equal(normalized.objects[1].fields[1].value,true);});
test('provider GIF export holds identity not cached media bytes',()=>{const b=M.board();b.objects=[M.node('media',{id:'g',provider:'giphy',providerId:'abc123',url:null})];const restored=M.validate(b);assert.equal(restored.objects[0].providerId,'abc123');assert.equal(restored.objects[0].url,null);});
