import {LabError,imageType} from './core.mjs';
import {now,project,storeFile} from './storage.mjs';
import {recordUsage} from './usage.mjs';

const MAX_BYTES=12*1024*1024,MAX_PIXELS=40_000_000;
const cleanText=(value,max=240)=>String(value||'').replace(/[\u0000-\u001f\u007f]/g,' ').replace(/\s+/g,' ').trim().slice(0,max);
function safeHttp(value,{https=false}={}){try{const url=new URL(value);if((https&&url.protocol!=='https:')||(!https&&!['http:','https:'].includes(url.protocol))||url.username||url.password)return '';return url.href;}catch{return '';}}

export function googleImageConfiguration(env){const cx=cleanText(env.GOOGLE_PSE_CX,200);return {configured:Boolean(cx),cx:cx||null,provider:'Google Programmable Search Element',integration:'standard_search_element',imageSearchAvailable:Boolean(cx),scope:cx?'configured_engine':'missing',scopeLabel:cx?'Configured engine':'Not configured',adSupported:true,legacyJsonApi:false};}
export function normalizeGoogleResult(value={}){const imageUrl=safeHttp(value.image?.url,{https:true})||safeHttp(value.url,{https:true}),thumbnailUrl=safeHttp(value.thumbnailImage?.url,{https:true}),contextUrl=safeHttp(value.contextUrl)||safeHttp(value.url);if(!imageUrl||!contextUrl)throw new LabError('This Google image result has no usable HTTPS image and source page.',422,'invalid_image_result');const dimension=n=>Number.isSafeInteger(Number(n))&&Number(n)>0?Number(n):null,titleNoFormatting=cleanText(value.titleNoFormatting,180)||null;return {provider:'google',title:titleNoFormatting||cleanText(value.title||'Untitled image',180),titleNoFormatting,url:safeHttp(value.url)||contextUrl,visibleUrl:cleanText(value.visibleUrl,240),contextUrl,imageUrl,thumbnailUrl,width:dimension(value.image?.width),height:dimension(value.image?.height),thumbnailWidth:dimension(value.thumbnailImage?.width),thumbnailHeight:dimension(value.thumbnailImage?.height),fileFormat:cleanText(value.fileFormat,80)||null,sourceHostname:new URL(contextUrl).hostname.replace(/^www\./,'')};}
export async function recordGoogleActivity(env,owner,projectId,input={}){await project(env,owner,projectId);const action=input.action;if(!['search_started','result_used'].includes(action))throw new LabError('Unsupported Google activity.');const activityId=cleanText(input.activityId,100);if(!activityId)throw new LabError('Google activity ID required.');await recordUsage(env,{idempotencyKey:`google:${action}:${owner}:${projectId}:${activityId}`,ownerId:owner,projectId,provider:'google',operation:action==='search_started'?'image_search':'image_result_used',outcome:'succeeded',searchCount:action==='search_started'?1:0,generatedOutputs:action==='result_used'?1:0,metadata:{queryLength:cleanText(input.query,160).length,destination:cleanText(input.destination,40)||null,localWorkshopActivity:true}});return {recorded:true};}

function ipv4(value){const parts=value.split('.');if(parts.length!==4||parts.some(part=>!/^\d{1,3}$/.test(part)||Number(part)>255))return null;return parts.map(Number);}
function assertPublicAddress(value){const parts=ipv4(value);if(parts&&(parts[0]===0||parts[0]===10||parts[0]===127||parts[0]===169&&parts[1]===254||parts[0]===172&&parts[1]>=16&&parts[1]<=31||parts[0]===192&&[0,2,168].includes(parts[1])||parts[0]===198&&[18,19,51].includes(parts[1])||parts[0]===203&&parts[1]===0&&parts[2]===113||parts[0]===100&&parts[1]>=64&&parts[1]<=127||parts[0]>=224))throw new LabError('Private image sources are not allowed.',422,'unsafe_image_source');const host=String(value).toLowerCase().replace(/^\[|\]$/g,'');if(host.includes(':')&&(/^(?:fc|fd|fe8|fe9|fea|feb)/i.test(host)||host==='::'||host==='::1'||host.startsWith('2001:db8')))throw new LabError('Private image sources are not allowed.',422,'unsafe_image_source');return true;}
export function assertPublicImageUrl(value){let url;try{url=new URL(value);}catch{throw new LabError('The image source is invalid.',422,'unsafe_image_source');}if(url.protocol!=='https:'||url.username||url.password||url.port)throw new LabError('Only public HTTPS image sources are allowed.',422,'unsafe_image_source');const host=url.hostname.toLowerCase().replace(/^\[|\]$/g,'');if(host==='localhost'||host.endsWith('.localhost')||host.endsWith('.local')||host.endsWith('.internal')||host==='metadata.google.internal'||host==='0.0.0.0')throw new LabError('Private image sources are not allowed.',422,'unsafe_image_source');assertPublicAddress(host);return url;}
export async function resolvePublicHost(hostname,fetcher=fetch){if(ipv4(hostname)||hostname.includes(':'))return assertPublicAddress(hostname);const addresses=[];for(const type of ['A','AAAA']){const url=new URL('https://cloudflare-dns.com/dns-query');url.searchParams.set('name',hostname);url.searchParams.set('type',type);let response;try{response=await fetcher(url,{headers:{Accept:'application/dns-json'},redirect:'manual',signal:AbortSignal.timeout(3000)});}catch{throw new LabError('The image host could not be verified safely.',422,'image_dns_unavailable');}if(!response.ok||response.status>=300&&response.status<400)throw new LabError('The image host could not be verified safely.',422,'image_dns_unavailable');const data=await response.json();for(const answer of data.Answer||[])if(answer.type===1||answer.type===28)addresses.push(answer.data);}if(!addresses.length)throw new LabError('The image host did not resolve to a public address.',422,'unsafe_image_source');for(const address of addresses)assertPublicAddress(address);return true;}

function dimensions(bytes,type){if(type.mime==='image/png'&&bytes.length>=24)return {width:bytes.readUInt32BE(16),height:bytes.readUInt32BE(20)};if(type.mime==='image/jpeg'){let i=2;while(i+9<bytes.length){if(bytes[i]!==0xff){i++;continue;}const marker=bytes[i+1],length=bytes.readUInt16BE(i+2);if([0xc0,0xc1,0xc2,0xc3,0xc5,0xc6,0xc7,0xc9,0xca,0xcb,0xcd,0xce,0xcf].includes(marker))return {height:bytes.readUInt16BE(i+5),width:bytes.readUInt16BE(i+7)};if(length<2)break;i+=2+length;}}if(type.mime==='image/webp'&&bytes.length>=30){const chunk=bytes.toString('ascii',12,16);if(chunk==='VP8X')return {width:1+bytes.readUIntLE(24,3),height:1+bytes.readUIntLE(27,3)};if(chunk==='VP8 '&&bytes[23]===0x9d&&bytes[24]===0x01&&bytes[25]===0x2a)return {width:bytes.readUInt16LE(26)&0x3fff,height:bytes.readUInt16LE(28)&0x3fff};if(chunk==='VP8L'&&bytes[20]===0x2f){const bits=bytes.readUInt32LE(21);return {width:(bits&0x3fff)+1,height:((bits>>>14)&0x3fff)+1};}}return null;}
export async function fetchBoundedImage(value,fetcher=fetch,resolver=resolvePublicHost){let current=assertPublicImageUrl(value);for(let redirects=0;redirects<=3;redirects++){await resolver(current.hostname,fetcher);const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),10000);let response;try{response=await fetcher(current,{redirect:'manual',headers:{Accept:'image/png,image/jpeg,image/webp'},signal:controller.signal});}catch(error){throw new LabError(error?.name==='AbortError'?'Image import timed out.':'The source image could not be reached.',502,'image_import_failed');}finally{clearTimeout(timer);}if([301,302,303,307,308].includes(response.status)){const location=response.headers.get('location');if(!location||redirects===3)throw new LabError('The image source redirected too many times.',422,'unsafe_image_source');current=assertPublicImageUrl(new URL(location,current).href);continue;}if(!response.ok)throw new LabError('The source image is unavailable.',502,'image_import_failed');const declared=response.headers.get('content-type')?.split(';')[0].trim().toLowerCase();if(!['image/png','image/jpeg','image/webp'].includes(declared))throw new LabError('The source did not return a supported image.',422,'unsupported_output');const length=Number(response.headers.get('content-length')||0);if(length>MAX_BYTES)throw new LabError('The source image exceeds the 12 MB import limit.',413,'image_too_large');const reader=response.body?.getReader();if(!reader)throw new LabError('The source image is unavailable.',502,'image_import_failed');const chunks=[];let count=0;for(;;){const {done,value:chunk}=await reader.read();if(done)break;count+=chunk.byteLength;if(count>MAX_BYTES){await reader.cancel();throw new LabError('The source image exceeds the 12 MB import limit.',413,'image_too_large');}chunks.push(Buffer.from(chunk));}const bytes=Buffer.concat(chunks),type=imageType(bytes);if(type.mime!==declared)throw new LabError('The source content did not match its image type.',422,'unsupported_output');const size=dimensions(bytes,type);if(size&&(size.width<1||size.height<1||size.width*size.height>MAX_PIXELS))throw new LabError('The source image dimensions exceed the safe import limit.',413,'image_dimensions_too_large');return {bytes,type,size,url:current.href};}}

export async function importGoogleImage(env,owner,projectId,value,destination,fetcher=fetch,resolver=resolvePublicHost){await project(env,owner,projectId);const result=normalizeGoogleResult(value),download=await fetchBoundedImage(result.imageUrl,fetcher,resolver);const asset=await storeFile(env,owner,projectId,download.bytes,{source:'google-images',provider:'google',title:result.title,sourceUrl:result.url,contextUrl:result.contextUrl,visibleUrl:result.visibleUrl,sourceHostname:result.sourceHostname,fileFormat:result.fileFormat,width:download.size?.width||result.width,height:download.size?.height||result.height,thumbnail:{url:result.thumbnailUrl,width:result.thumbnailWidth,height:result.thumbnailHeight},rightsNotice:'Search results are references. Verify usage rights before publication.'});await recordUsage(env,{idempotencyKey:`google-use:${owner}:${projectId}:${cleanText(value.activityId,100)||crypto.randomUUID()}`,ownerId:owner,projectId,provider:'google',operation:'image_result_used',outcome:'succeeded',generatedOutputs:1,metadata:{destination:cleanText(destination,40),localWorkshopActivity:true,usedAt:now()}});return {asset};}
