import {createHmac,timingSafeEqual} from 'node:crypto';
import {LabError} from './core.mjs';
import {dbOf,digest,id,now,project,storeFile} from './storage.mjs';
import {resolveCredential} from './provider-profiles.mjs';
import {fetchBoundedImage} from './google-images.mjs';
import {rateFields,recordUsage} from './usage.mjs';

const PROVIDERS=new Set(['pexels','pixabay','unsplash']);
const ORIENTATIONS={pexels:new Set(['','landscape','portrait','square']),pixabay:new Set(['','horizontal','vertical']),unsplash:new Set(['','landscape','portrait','squarish'])};
const PIXABAY_TYPES=new Set(['','photo','illustration','vector']);
const PIXABAY_CATEGORIES=new Set(['','backgrounds','fashion','nature','science','education','feelings','health','people','religion','places','animals','industry','computer','food','sports','transportation','travel','buildings','business','music']);
const PEXELS_SIZES=new Set(['','large','medium','small']);
const safeText=(value,max=240)=>String(value||'').replace(/[\u0000-\u001f\u007f]/g,' ').replace(/\s+/g,' ').trim().slice(0,max);
function https(value){try{const url=new URL(value);return url.protocol==='https:'&&!url.username&&!url.password?url.href:'';}catch{return '';}}
function providerOf(value){const provider=String(value||'').toLowerCase();if(!PROVIDERS.has(provider))throw new LabError('Choose Pexels, Pixabay, or Unsplash.');return provider;}
function number(value,min,max,name){const n=Number(value);if(!Number.isSafeInteger(n)||n<min||n>max)throw new LabError(`Invalid ${name}.`);return n;}
function oneOf(value,set,name){const v=String(value||'').toLowerCase();if(!set.has(v))throw new LabError(`Unsupported ${name}.`);return v;}
function vaultSigningKey(env){const raw=Buffer.from(String(env.LAB_VAULT_MASTER_KEY_V1||''),'base64url');if(raw.length!==32)throw new LabError('The provider profile vault is unavailable.',503,'vault_unavailable');return raw;}
function token(env,payload){const body=Buffer.from(JSON.stringify(payload)).toString('base64url'),sig=createHmac('sha256',vaultSigningKey(env)).update(body).digest('base64url');return `${body}.${sig}`;}
function verifyToken(env,value,owner,projectId){const [body,sig,extra]=String(value||'').split('.');if(!body||!sig||extra||body.length>12000)throw invalid();const expected=createHmac('sha256',vaultSigningKey(env)).update(body).digest(),actual=Buffer.from(sig,'base64url');if(actual.length!==expected.length||!timingSafeEqual(actual,expected))throw invalid();let item;try{item=JSON.parse(Buffer.from(body,'base64url').toString());}catch{throw invalid();}if(item.owner!==owner||item.projectId!==projectId||item.exp<Date.now()||item.exp>Date.now()+31*60_000||!PROVIDERS.has(item.provider)||!https(item.imageUrl)||!https(item.sourceUrl))throw invalid();return item;}
function invalid(){return new LabError('This stock-media result is invalid or expired.',400,'invalid_stock_result');}
function resultToken(env,owner,projectId,item){return token(env,{...item,owner,projectId,exp:Date.now()+30*60_000});}
function attribution(provider,item){if(provider==='pexels')return {provider:'Pexels',creator:item.creator,creatorUrl:item.creatorUrl,providerUrl:'https://www.pexels.com/',licenseUrl:'https://www.pexels.com/license/'};if(provider==='pixabay')return {provider:'Pixabay',creator:item.creator,creatorUrl:item.creatorUrl,providerUrl:'https://pixabay.com/',licenseUrl:'https://pixabay.com/service/license-summary/'};return {provider:'Unsplash',creator:item.creator,creatorUrl:item.creatorUrl,providerUrl:'https://unsplash.com/?utm_source=third_railify_lab&utm_medium=referral',licenseUrl:'https://unsplash.com/license'};}

export async function searchStockMedia(env,owner,projectId,requestUrl,fetcher=fetch){await project(env,owner,projectId);const input=new URL(requestUrl),provider=providerOf(input.searchParams.get('provider')),query=safeText(input.searchParams.get('q'),160);if(query.length<2)throw new LabError('Enter a search of 2–160 characters.');const page=number(input.searchParams.get('page')||1,1,100,'page'),orientation=oneOf(input.searchParams.get('orientation'),ORIENTATIONS[provider],'orientation'),credential=await resolveCredential(env,owner,provider,'',input.searchParams.get('profileId')||''),usageKey=`stock:${owner}:${projectId}:${provider}:${await digest(input.searchParams.toString())}`;let target,headers={Accept:'application/json'},normalize;
  if(provider==='pexels'){target=new URL('https://api.pexels.com/v1/search');target.searchParams.set('query',query);target.searchParams.set('page',String(page));target.searchParams.set('per_page','24');if(orientation)target.searchParams.set('orientation',orientation);const size=oneOf(input.searchParams.get('size'),PEXELS_SIZES,'size');if(size)target.searchParams.set('size',size);const color=safeText(input.searchParams.get('color'),20);if(color&&!/^(?:red|orange|yellow|green|turquoise|blue|violet|pink|brown|black|gray|white|#[a-f0-9]{6})$/i.test(color))throw new LabError('Unsupported Pexels color.');if(color)target.searchParams.set('color',color);headers.Authorization=credential.secret;normalize=data=>({items:(data.photos||[]).map(photo=>({provider,id:String(photo.id),title:safeText(photo.alt||`Pexels photo ${photo.id}`,180),imageUrl:https(photo.src?.original),previewUrl:https(photo.src?.large||photo.src?.medium),sourceUrl:https(photo.url),width:Number(photo.width)||null,height:Number(photo.height)||null,creator:safeText(photo.photographer,120),creatorUrl:https(photo.photographer_url),downloadLocation:null,mediaType:'photo'})),total:Number(data.total_results)||0,hasMore:Boolean(data.next_page)});}
  if(provider==='pixabay'){target=new URL('https://pixabay.com/api/');target.searchParams.set('key',credential.secret);target.searchParams.set('q',query);target.searchParams.set('page',String(page));target.searchParams.set('per_page','24');target.searchParams.set('safesearch',input.searchParams.get('safe')==='false'?'false':'true');if(orientation)target.searchParams.set('orientation',orientation);const type=oneOf(input.searchParams.get('type'),PIXABAY_TYPES,'media type'),category=oneOf(input.searchParams.get('category'),PIXABAY_CATEGORIES,'category');if(type)target.searchParams.set('image_type',type);if(category)target.searchParams.set('category',category);const colors=safeText(input.searchParams.get('color'),60);if(colors&&!/^(?:grayscale|transparent|red|orange|yellow|green|turquoise|blue|lilac|pink|white|gray|black|brown)(?:,(?:grayscale|transparent|red|orange|yellow|green|turquoise|blue|lilac|pink|white|gray|black|brown))*$/.test(colors))throw new LabError('Unsupported Pixabay color.');if(colors)target.searchParams.set('colors',colors);normalize=data=>({items:(data.hits||[]).map(photo=>({provider,id:String(photo.id),title:safeText(photo.tags||`Pixabay image ${photo.id}`,180),imageUrl:https(photo.largeImageURL),previewUrl:https(photo.webformatURL),sourceUrl:https(photo.pageURL),width:Number(photo.imageWidth)||null,height:Number(photo.imageHeight)||null,creator:safeText(photo.user,120),creatorUrl:https(`https://pixabay.com/users/${photo.user}-${photo.user_id}/`),downloadLocation:null,mediaType:safeText(photo.type,30)||'photo'})),total:Number(data.totalHits)||0,hasMore:page*24<Number(data.totalHits||0)});}
  if(provider==='unsplash'){target=new URL('https://api.unsplash.com/search/photos');target.searchParams.set('query',query);target.searchParams.set('page',String(page));target.searchParams.set('per_page','24');if(orientation)target.searchParams.set('orientation',orientation);headers.Authorization='Client-ID '+credential.secret;headers['Accept-Version']='v1';normalize=data=>({items:(data.results||[]).map(photo=>({provider,id:String(photo.id),title:safeText(photo.alt_description||photo.description||`Unsplash photo ${photo.id}`,180),imageUrl:https(photo.urls?.regular),previewUrl:https(photo.urls?.small),sourceUrl:withUtm(photo.links?.html),width:Number(photo.width)||null,height:Number(photo.height)||null,creator:safeText(photo.user?.name,120),creatorUrl:withUtm(photo.user?.links?.html),downloadLocation:https(photo.links?.download_location),mediaType:'photo'})),total:Number(data.total)||0,hasMore:page<Number(data.total_pages||0)});}
  const cacheKey=provider==='pixabay'?await digest(target.origin+target.pathname+'?'+[...target.searchParams].filter(([key])=>key!=='key').map(([key,value])=>`${key}=${value}`).join('&')):null;if(cacheKey){const cached=await dbOf(env).prepare('SELECT response_json FROM stock_search_cache WHERE cache_key=? AND expires_at>?').bind(cacheKey,now()).first();if(cached){const result=JSON.parse(cached.response_json);await recordUsage(env,{idempotencyKey:usageKey+':cache',ownerId:owner,projectId,provider,profileId:credential.profileId,fingerprint:credential.fingerprint,operation:'stock_search',outcome:'succeeded',searchCount:1,cacheStatus:'hit',metadata:{queryLength:query.length,page}});return finalize(env,owner,projectId,result,provider,query,page,true,credential);}}
  let response,data;try{response=await fetcher(target,{headers,redirect:'manual',signal:AbortSignal.timeout(12000)});const text=await boundedText(response,3*1024*1024);try{data=JSON.parse(text);}catch{throw new LabError(`${providerName(provider)} returned an invalid response.`,502,'stock_provider_invalid');}if(!response.ok)throw new LabError(safeText(data?.error||data?.message||`${providerName(provider)} search failed (${response.status}).`,300),response.status===429?429:502,response.status===429?'stock_quota':'stock_provider_error');const normalized=normalize(data);if(cacheKey)await dbOf(env).prepare('INSERT OR REPLACE INTO stock_search_cache(cache_key,provider,response_json,created_at,expires_at) VALUES(?,?,?,?,?)').bind(cacheKey,provider,JSON.stringify(normalized),now(),new Date(Date.now()+24*60*60*1000).toISOString()).run();await recordUsage(env,{idempotencyKey:usageKey+':provider',ownerId:owner,projectId,provider,profileId:credential.profileId,fingerprint:credential.fingerprint,operation:'stock_search',outcome:'succeeded',searchCount:1,cacheStatus:cacheKey?'miss':'not_applicable',...rateFields(response.headers),metadata:{queryLength:query.length,page}});return finalize(env,owner,projectId,normalized,provider,query,page,false,credential);}catch(error){await recordUsage(env,{idempotencyKey:usageKey+':provider',ownerId:owner,projectId,provider,profileId:credential.profileId,fingerprint:credential.fingerprint,operation:'stock_search',outcome:'failed',searchCount:1,cacheStatus:cacheKey?'miss':'not_applicable',...rateFields(response?.headers),metadata:{status:response?.status||null}}).catch(()=>{});throw error;}}

function finalize(env,owner,projectId,result,provider,query,page,cacheHit,credential){const items=result.items.filter(item=>item.imageUrl&&item.previewUrl&&item.sourceUrl).map(item=>({...item,attribution:attribution(provider,item),token:resultToken(env,owner,projectId,{...item,profileId:credential.profileId,fingerprint:credential.fingerprint})}));return {provider,query,page,items,total:result.total,hasMore:result.hasMore,cacheHit,rightsUrl:items[0]?.attribution.licenseUrl||null,rateNotice:cacheHit?'Pixabay result cache · provider not called':null};}
function providerName(provider){return provider[0].toUpperCase()+provider.slice(1);}
function withUtm(value){const safe=https(value);if(!safe)return '';const url=new URL(safe);url.searchParams.set('utm_source','third_railify_lab');url.searchParams.set('utm_medium','referral');return url.href;}
async function boundedText(response,max){if(!response.body)return '';const reader=response.body.getReader(),chunks=[];let size=0;for(;;){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>max){await reader.cancel();throw new LabError('Stock provider response was too large.',502,'stock_provider_invalid');}chunks.push(Buffer.from(value));}return Buffer.concat(chunks).toString('utf8');}

export async function selectStockResult(env,owner,projectId,value,destination,fetcher=fetch){await project(env,owner,projectId);const item=verifyToken(env,value,owner,projectId),metadata={source:`stock-${item.provider}`,provider:item.provider,providerId:item.id,title:item.title,sourceUrl:item.sourceUrl,creator:item.creator,creatorUrl:item.creatorUrl,attribution:attribution(item.provider,item),width:item.width,height:item.height};if(item.provider==='unsplash'){await trackUnsplash(env,owner,projectId,item,fetcher);const referenceId=id(),createdAt=now();await dbOf(env).prepare('INSERT INTO stock_references(id,owner_id,project_id,provider,provider_id,title,source_url,image_url,creator_name,creator_url,attribution_json,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').bind(referenceId,owner,projectId,'unsplash',item.id,item.title,item.sourceUrl,item.imageUrl,item.creator||null,item.creatorUrl||null,JSON.stringify(metadata.attribution),createdAt).run();return {externalAsset:{...metadata,name:item.title,id:`stock:${referenceId}`,url:item.imageUrl,kind:'external-image',createdAt,providerBacked:true},compatible:{chat:true,generation:'model-dependent',compose:false}};}const download=await fetchBoundedImage(item.imageUrl,fetcher),asset=await storeFile(env,owner,projectId,download.bytes,{...metadata,width:download.size?.width||item.width,height:download.size?.height||item.height});await dbOf(env).prepare('INSERT INTO stock_references(id,owner_id,project_id,provider,provider_id,title,source_url,image_url,creator_name,creator_url,attribution_json,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').bind(id(),owner,projectId,item.provider,item.id,item.title,item.sourceUrl,asset.url,item.creator||null,item.creatorUrl||null,JSON.stringify(metadata.attribution),now()).run();await recordUsage(env,{idempotencyKey:`stock-use:${owner}:${projectId}:${item.provider}:${item.id}:${destination}`,ownerId:owner,projectId,provider:item.provider,profileId:item.profileId,fingerprint:item.fingerprint,operation:'stock_result_used',outcome:'succeeded',generatedOutputs:1,metadata:{destination}});return {asset,compatible:{chat:true,generation:true,compose:true}};}

async function trackUnsplash(env,owner,projectId,item,fetcher){if(!item.downloadLocation)throw new LabError('Unsplash did not supply its required download tracking endpoint.',409,'unsplash_tracking_unavailable');const credential=await resolveCredential(env,owner,'unsplash','',item.profileId||'');let response;try{response=await fetcher(item.downloadLocation,{headers:{Authorization:'Client-ID '+credential.secret,'Accept-Version':'v1'},redirect:'manual',signal:AbortSignal.timeout(10000)});if(!response.ok)throw new LabError('Unsplash selection tracking was rejected; the image was not selected.',502,'unsplash_tracking_failed');await recordUsage(env,{idempotencyKey:`unsplash-download:${owner}:${projectId}:${item.id}`,ownerId:owner,projectId,provider:'unsplash',profileId:credential.profileId,fingerprint:credential.fingerprint,operation:'download_tracking',outcome:'succeeded',...rateFields(response.headers),metadata:{providerId:item.id}});}catch(error){await recordUsage(env,{idempotencyKey:`unsplash-download:${owner}:${projectId}:${item.id}`,ownerId:owner,projectId,provider:'unsplash',profileId:credential.profileId,fingerprint:credential.fingerprint,operation:'download_tracking',outcome:'failed',metadata:{providerId:item.id}}).catch(()=>{});throw error;}}

export async function externalAttachment(env,owner,value){const match=String(value||'').match(/^stock:([a-f0-9-]{36})$/);if(!match)return null;const row=await dbOf(env).prepare('SELECT * FROM stock_references WHERE id=? AND owner_id=?').bind(match[1],owner).first();if(!row)return null;return {id:value,kind:'external-image',mime:'image/jpeg',name:row.title,url:row.image_url,provider:row.provider,attribution:JSON.parse(row.attribution_json)};}

export async function testStockProvider(env,owner,provider,profileId='',fetcher=fetch){provider=providerOf(provider);const credential=await resolveCredential(env,owner,provider,'',profileId);let url,headers={Accept:'application/json'};if(provider==='pexels'){url='https://api.pexels.com/v1/curated?per_page=1';headers.Authorization=credential.secret;}if(provider==='pixabay')url='https://pixabay.com/api/?key='+encodeURIComponent(credential.secret)+'&per_page=3&safesearch=true';if(provider==='unsplash'){url='https://api.unsplash.com/photos?per_page=1';headers.Authorization='Client-ID '+credential.secret;headers['Accept-Version']='v1';}let response;try{response=await fetcher(url,{headers,redirect:'manual',signal:AbortSignal.timeout(10000)});await response.body?.cancel();if(!response.ok)throw new LabError(`${providerName(provider)} authentication was rejected (${response.status}).`,[401,403].includes(response.status)?response.status:502,'stock_provider_test_failed');await recordUsage(env,{idempotencyKey:`stock-test:${owner}:${provider}:${credential.profileId}:${Date.now()}`,ownerId:owner,provider,profileId:credential.profileId,fingerprint:credential.fingerprint,operation:'connection_test',outcome:'succeeded',...rateFields(response.headers)});return {message:`${providerName(provider)} authentication verified.`};}catch(error){await recordUsage(env,{idempotencyKey:`stock-test:${owner}:${provider}:${credential.profileId}:${Date.now()}`,ownerId:owner,provider,profileId:credential.profileId,fingerprint:credential.fingerprint,operation:'connection_test',outcome:'failed',...rateFields(response?.headers)}).catch(()=>{});throw error;}}
