import {LabError} from './core.mjs';
import {dbOf,id,now} from './storage.mjs';

const PROVIDERS=new Set(['replicate','openai','xai','pexels','pixabay','unsplash','google']);
const COST_STATES=new Set(['actual','estimated','unknown']);
const integer=value=>Number.isSafeInteger(Number(value))&&Number(value)>=0?Number(value):null;
const moneyMicros=value=>typeof value==='number'&&Number.isFinite(value)&&value>=0?Math.round(value*1_000_000):null;
const safeId=value=>String(value||'').replace(/[^\w:.-]/g,'').slice(0,200)||null;
const safeJson=value=>JSON.stringify(value&&typeof value==='object'?value:{}).slice(0,8000);

export async function recordUsage(env,event){const provider=String(event.provider||'').toLowerCase();if(!PROVIDERS.has(provider))throw new LabError('Unsupported usage provider.');const costState=COST_STATES.has(event.costState)?event.costState:'unknown',timestamp=event.startedAt||now(),key=String(event.idempotencyKey||'').slice(0,240);if(!key)throw new LabError('Usage idempotency key required.');const values={inputTokens:integer(event.inputTokens),outputTokens:integer(event.outputTokens),cachedTokens:integer(event.cachedTokens),reasoningTokens:integer(event.reasoningTokens),generatedOutputs:integer(event.generatedOutputs),searchCount:integer(event.searchCount),toolCalls:integer(event.toolCalls),providerCostMicros:event.providerCostMicros??moneyMicros(event.providerCost),estimatedCostMicros:event.estimatedCostMicros??moneyMicros(event.estimatedCost),rateLimitLimit:integer(event.rateLimitLimit),rateLimitRemaining:integer(event.rateLimitRemaining)};await dbOf(env).prepare(`INSERT INTO provider_usage_events(id,idempotency_key,owner_id,project_id,job_id,conversation_id,provider,key_profile_id,key_fingerprint,model,operation,started_at,completed_at,outcome,provider_request_id,input_tokens,output_tokens,cached_tokens,reasoning_tokens,generated_outputs,search_count,tool_calls,provider_cost_micros,estimated_cost_micros,cost_state,cache_status,rate_limit_limit,rate_limit_remaining,rate_limit_reset,safe_metadata_json)
  VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
  ON CONFLICT(idempotency_key) DO UPDATE SET completed_at=excluded.completed_at,outcome=excluded.outcome,provider_request_id=COALESCE(excluded.provider_request_id,provider_usage_events.provider_request_id),input_tokens=COALESCE(excluded.input_tokens,provider_usage_events.input_tokens),output_tokens=COALESCE(excluded.output_tokens,provider_usage_events.output_tokens),cached_tokens=COALESCE(excluded.cached_tokens,provider_usage_events.cached_tokens),reasoning_tokens=COALESCE(excluded.reasoning_tokens,provider_usage_events.reasoning_tokens),generated_outputs=COALESCE(excluded.generated_outputs,provider_usage_events.generated_outputs),search_count=COALESCE(excluded.search_count,provider_usage_events.search_count),tool_calls=COALESCE(excluded.tool_calls,provider_usage_events.tool_calls),provider_cost_micros=COALESCE(excluded.provider_cost_micros,provider_usage_events.provider_cost_micros),estimated_cost_micros=COALESCE(excluded.estimated_cost_micros,provider_usage_events.estimated_cost_micros),cost_state=excluded.cost_state,cache_status=COALESCE(excluded.cache_status,provider_usage_events.cache_status),rate_limit_limit=COALESCE(excluded.rate_limit_limit,provider_usage_events.rate_limit_limit),rate_limit_remaining=COALESCE(excluded.rate_limit_remaining,provider_usage_events.rate_limit_remaining),rate_limit_reset=COALESCE(excluded.rate_limit_reset,provider_usage_events.rate_limit_reset),safe_metadata_json=excluded.safe_metadata_json`).bind(id(),key,String(event.ownerId||''),event.projectId||null,event.jobId||null,event.conversationId||null,provider,event.profileId||null,event.fingerprint||null,String(event.model||'').slice(0,180)||null,String(event.operation||'request').slice(0,80),timestamp,event.completedAt||now(),String(event.outcome||'unknown').slice(0,40),safeId(event.providerRequestId),values.inputTokens,values.outputTokens,values.cachedTokens,values.reasoningTokens,values.generatedOutputs,values.searchCount,values.toolCalls,values.providerCostMicros,values.estimatedCostMicros,costState,event.cacheStatus||null,values.rateLimitLimit,values.rateLimitRemaining,event.rateLimitReset?String(event.rateLimitReset).slice(0,80):null,safeJson(event.metadata)).run();}

export function usageFromResponse(usage={}){return {inputTokens:integer(usage.input_tokens??usage.prompt_tokens),outputTokens:integer(usage.output_tokens??usage.completion_tokens),cachedTokens:integer(usage.input_tokens_details?.cached_tokens??usage.prompt_tokens_details?.cached_tokens),reasoningTokens:integer(usage.output_tokens_details?.reasoning_tokens??usage.completion_tokens_details?.reasoning_tokens)};}
export function providerCostFields(value={}){const amount=value.cost??value.total_cost??value.usage?.cost??value.usage?.total_cost;return typeof amount==='number'&&Number.isFinite(amount)&&amount>=0?{providerCost:amount,costState:'actual'}:{costState:'unknown'};}
export function rateFields(headers){return {rateLimitLimit:integer(headers?.get?.('x-ratelimit-limit')),rateLimitRemaining:integer(headers?.get?.('x-ratelimit-remaining')),rateLimitReset:headers?.get?.('x-ratelimit-reset')||null};}

export async function usageDashboard(env,auth,url){const range=new Set(['24h','7d','30d','90d']).has(url.searchParams.get('range'))?url.searchParams.get('range'):'30d',days={"24h":1,"7d":7,"30d":30,"90d":90}[range],since=new Date(Date.now()-days*86400000).toISOString(),params=[since],where=['started_at>=?'];const provider=url.searchParams.get('provider');if(provider&&PROVIDERS.has(provider)){where.push('provider=?');params.push(provider);}const model=String(url.searchParams.get('model')||'').slice(0,180);if(model){where.push('model=?');params.push(model);}const profile=String(url.searchParams.get('profile')||'').slice(0,100);if(profile){where.push('key_profile_id=?');params.push(profile);}let accountId=auth.owner;if(url.searchParams.get('account')&&auth.policy.canManageProviders)accountId=String(url.searchParams.get('account')).slice(0,100);where.push('owner_id=?');params.push(accountId);const clause=where.join(' AND '),db=dbOf(env);const [summary,providers,daysRows,recent,storage]=await Promise.all([
  db.prepare(`SELECT count(*) requests,COALESCE(sum(input_tokens),0)+COALESCE(sum(output_tokens),0) tokens,COALESCE(sum(generated_outputs),0) outputs,COALESCE(sum(search_count),0) searches,COALESCE(sum(tool_calls),0) tool_calls,sum(provider_cost_micros) actual_micros,sum(estimated_cost_micros) estimated_micros,sum(CASE WHEN cost_state='unknown' THEN 1 ELSE 0 END) unknown_count FROM provider_usage_events WHERE ${clause}`).bind(...params).first(),
  db.prepare(`SELECT provider,count(*) requests,COALESCE(sum(input_tokens),0)+COALESCE(sum(output_tokens),0) tokens,COALESCE(sum(generated_outputs),0) outputs,COALESCE(sum(search_count),0) searches,sum(provider_cost_micros) actual_micros,sum(estimated_cost_micros) estimated_micros,min(rate_limit_remaining) rate_remaining,max(rate_limit_limit) rate_limit FROM provider_usage_events WHERE ${clause} GROUP BY provider ORDER BY requests DESC`).bind(...params).all(),
  db.prepare(`SELECT substr(started_at,1,10) day,count(*) requests,COALESCE(sum(input_tokens),0)+COALESCE(sum(output_tokens),0) tokens,COALESCE(sum(search_count),0) searches FROM provider_usage_events WHERE ${clause} GROUP BY substr(started_at,1,10) ORDER BY day`).bind(...params).all(),
  db.prepare(`SELECT provider,model,operation,outcome,cost_state,provider_cost_micros,estimated_cost_micros,started_at,key_profile_id FROM provider_usage_events WHERE ${clause} ORDER BY COALESCE(provider_cost_micros,estimated_cost_micros,0) DESC,started_at DESC LIMIT 20`).bind(...params).all(),
  db.prepare("SELECT count(*) files,COALESCE(sum(CAST(json_extract(metadata,'$.bytes') AS INTEGER)),0) bytes FROM files WHERE owner_id=? AND status='ready'").bind(accountId).first(),
]);return {range,accountId,summary,providers:providers.results||[],series:daysRows.results||[],recent:recent.results||[],storage};}
