"""Offline fixture-backed UI test. Not a native persistence or live-provider test."""
import os
from playwright.sync_api import sync_playwright
from pathlib import Path
import json,time
ROOT=Path(__file__).resolve().parents[2];R=ROOT/'public';OUT=ROOT/'.test-artifacts';OUT.mkdir(exist_ok=True)
base=R.joinpath('index.html').read_text().replace('<link rel="stylesheet" href="/styles.css">','<style>'+R.joinpath('styles.css').read_text()+'</style>')
base=base.replace('<script src="/model.js"></script>','<script>'+Path(__file__).with_name('render_fixture.js').read_text()+'</script><script>'+R.joinpath('model.js').read_text()+'</script>').replace('<script src="/seed.js"></script>','<script>'+R.joinpath('seed.js').read_text()+'</script>').replace('<script src="/app.js"></script>','<script>'+R.joinpath('app.js').read_text()+'</script>')
results={'mode':'Managed Chromium, set_content, test-only in-memory IndexedDB API fixture; no navigation policy changed. Provider searches not called.','checks':[],'viewports':[],'pageErrors':[]}
def check(name,truth=True):
 assert truth,name
 results['checks'].append(name)
 print('PASS',name,flush=True)
with sync_playwright() as p:
 browser=p.chromium.launch(executable_path=os.environ.get('NOTESPACE_BROWSER','/usr/bin/chromium'),headless=True,args=['--no-sandbox'])
 for width,height in [(1920,1080),(1440,960),(768,1024),(390,844)]:
  page=browser.new_page(viewport={'width':width,'height':height},reduced_motion='reduce')
  page.set_default_timeout(5000)
  page.on('pageerror',lambda e:results['pageErrors'].append(str(e)))
  page.set_content(base,wait_until='domcontentloaded')
  page.wait_for_function('window.NotespacePOC?.getBoard()?.objects.length===12',timeout=10000)
  page.wait_for_timeout(350)
  page.evaluate("document.querySelectorAll('.toast').forEach(n=>n.remove())")
  page.screenshot(path=str(OUT/f'board-{width}.png'))
  overflow=page.evaluate('document.documentElement.scrollWidth>innerWidth')
  check(f'{width}px shell no horizontal overflow',not overflow)
  check(f'{width}px 12 live objects including nested content',page.locator('.board-object').count()==12)
  page.locator('.main-rail [data-action=media]').click()
  page.screenshot(path=str(OUT/f'media-{width}.png'))
  check(f'{width}px media modal contained',page.locator('.modal').bounding_box()['width']<=width)
  page.locator('[data-action=media-tab][data-tab=stickers]').click()
  check(f'{width}px 3 real bundled artwork choices',page.locator('.gif-result').count()==3)
  page.screenshot(path=str(OUT/f'stickers-{width}.png'))
  page.locator('.modal-header [data-action=close-modal]').click()
  page.locator('.main-rail [data-action=appearance]').click()
  page.locator('[data-action=choose-bg-mode][data-mode=gradient]').click()
  page.locator('#bg-pattern').select_option('grid')
  page.locator('[data-action=save-appearance]').click()
  page.evaluate('NotespacePOC.flush()')
  check(f'{width}px background changes persisted',page.evaluate("NotespacePOC.getBoard().background.pattern==='grid' && NotespacePOC.getBoard().background.mode==='gradient'"))
  page.locator('.main-rail [data-action=tasks]').click()
  check(f'{width}px honey-do view exposes all four tasks',page.locator('.todo-task').count()==4)
  page.locator('.todo-task').nth(1).locator('[data-action=check-task]').click()
  page.evaluate('NotespacePOC.flush()')
  check(f'{width}px checklist toggle updates real board',page.evaluate("NotespacePOC.getBoard().objects.find(n=>n.id==='honey-do').items[1].done"))
  page.screenshot(path=str(OUT/f'tasks-{width}.png'))
  page.locator('#library-page [data-action=canvas]').click()
  if width==1440:
   page.locator('[data-id=idea-one]').dblclick(position={'x':50,'y':50})
   page.locator('#edit-title').fill('Real editable idea')
   page.locator('#edit-text').fill('Keep this after reopening the board.')
   page.locator('#edit-tags').fill('tested, tomorrow')
   page.locator('[data-action=save-node]').click();page.evaluate('NotespacePOC.flush()')
   check('content editor saves note fields',page.evaluate("NotespacePOC.getBoard().objects.find(n=>n.id==='idea-one').title==='Real editable idea'"))
   # Reopen reads the saved document via storage API, rather than retaining editor state.
   page.evaluate("NotespacePOC.loadBoard('vn7TnJ5')")
   check('saved board reopen preserves content and media',page.evaluate("NotespacePOC.getBoard().objects.find(n=>n.id==='idea-one').title==='Real editable idea' && !!NotespacePOC.getBoard().objects.find(n=>n.id==='spark-sticker').assetId"))
   page.evaluate("NotespacePOC.select('idea-one')")
   page.locator('[data-action=add-property]').click()
   props=page.locator('[data-prop-key]');props.last.fill('priority');props.last.blur()
   page.locator('[data-prop-value]').last.fill('high');page.locator('[data-prop-value]').last.blur()
   page.evaluate('NotespacePOC.flush()')
   check('custom property editor saves metadata',page.evaluate("NotespacePOC.getBoard().objects.find(n=>n.id==='idea-one').fields.some(f=>f.key==='priority'&&f.value==='high')"))
   page.screenshot(path=str(OUT/'inspector-1440.png'))
   page.keyboard.press('Control+f');page.locator('#find-input').fill('tomorrow')
   check('find locates tags',page.locator('.find-result').count()==1)
   page.locator('.find-result').click();page.screenshot(path=str(OUT/'find-1440.png'));page.keyboard.press('Escape')
   page.evaluate('NotespacePOC.fitBoard()')
   # Use actual pointer dragging to verify parenting/camera math.
   box=page.locator('[data-id=frame-ideas]').bounding_box()
   before=page.evaluate("NotespacePOC.getBoard().objects.find(n=>n.id==='frame-ideas').x")
   z=page.evaluate('NotespacePOC.getCamera().z')
   page.mouse.move(box['x']+55,box['y']+20);page.mouse.down();page.mouse.move(box['x']+55+30,box['y']+20+18,steps=8);page.mouse.up();page.evaluate('NotespacePOC.flush()')
   check('dragging container moves parent with children intact',page.evaluate("NotespacePOC.getBoard().objects.find(n=>n.id==='frame-ideas').x")>before and page.evaluate("NotespacePOC.getBoard().objects.find(n=>n.id==='idea-one').parentId==='frame-ideas'"))
   page.keyboard.press('Control+z');page.evaluate('NotespacePOC.flush()');check('undo restores container movement',abs(page.evaluate("NotespacePOC.getBoard().objects.find(n=>n.id==='frame-ideas').x")-before)<.001)
   # Real upload input with original animated GIF bytes.
   page.locator('#media-file').set_input_files(str(R/'media/spark.gif'));page.wait_for_function('NotespacePOC.getBoard().objects.length===13');page.evaluate('NotespacePOC.flush()')
   check('animated GIF upload creates persistent media object',page.evaluate("NotespacePOC.getBoard().objects.at(-1).mime==='image/gif'"))
   image=page.locator('.board-object.media-object').last.locator('img');check('uploaded GIF is decoded by browser',image.evaluate('(i)=>i.naturalWidth===240 && i.naturalHeight===220'))
   page.evaluate('NotespacePOC.fitBoard()')
   page.locator('[data-action=cinema]').click();page.screenshot(path=str(OUT/'cinema-1440.png'))
   check('cinema removes chrome but retains toolbar',page.locator('.tool-dock').is_visible() and not page.locator('.app-header').is_visible())
   page.locator('.board-actions [data-action=inspector]').click()
   check('cinema full inspector remains accessible',page.locator('#inspector').is_visible())
   page.screenshot(path=str(OUT/'cinema-inspector-1440.png'))
   page.locator('#inspector [data-action=inspector]').click()
   page.keyboard.press('Escape')
   page.locator('.board-actions [data-action=share]').click();page.screenshot(path=str(OUT/'share-1440.png'))
   check('share clearly identifies local vs unpublished address','not active' in page.locator('.modal').inner_text())
   page.locator('.modal-header [data-action=close-modal]').click()
  page.locator('.main-rail [data-action=library]').click();page.screenshot(path=str(OUT/f'library-{width}.png'))
  check(f'{width}px library renders two stored boards',page.locator('.board-card').count()==2)
  page.locator('[data-action=new-board]').click();page.locator('#new-board-title').fill('Acceptance blank');page.locator('[data-action=create-board]').click()
  page.wait_for_function("NotespacePOC.getBoard().title==='Acceptance blank'")
  check(f'{width}px new blank board is real and empty',page.evaluate('NotespacePOC.getBoard().objects.length===0'))
  # Click-to-place a real sticky note through the toolbar.
  page.locator('[data-tool=note]').click();viewport=page.locator('#viewport').bounding_box();page.mouse.click(viewport['x']+viewport['width']*.4,viewport['y']+viewport['height']*.4)
  page.evaluate('NotespacePOC.flush()');check(f'{width}px toolbar creates a sticky note',page.evaluate('NotespacePOC.getBoard().objects.length===1'))
  page.keyboard.press('Control+d');page.evaluate('NotespacePOC.flush()');check(f'{width}px duplicate works',page.evaluate('NotespacePOC.getBoard().objects.length===2'))
  page.keyboard.press('Delete');page.evaluate('NotespacePOC.flush()');check(f'{width}px delete works',page.evaluate('NotespacePOC.getBoard().objects.length===1'))
  results['viewports'].append({'width':width,'height':height,'overflow':overflow})
  page.close()
 browser.close()
assert not results['pageErrors'],results['pageErrors']
OUT.joinpath('browser-checks.json').write_text(json.dumps(results,indent=2))
print('TOTAL',len(results['checks']))
